# Use an official Node.js runtime as the base image
FROM node:16 as build-stage

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --force

# RUN npm i bcrypt

# Copy app source code to the working directory
COPY . .

# Build the app (if applicable)
RUN npm run build

# Database Migration 
# RUN npm run seed:users

# env
# ENV PORT=3333
# ENV DB_HOST=139.59.244.26
# ENV DB_PORT=3306
# ENV DB_USERNAME=root
# ENV DB_PASSWORD=VkX182wRRg7gB1EbvUnrw7a2LjXTKk7ncb3aE=
# ENV DB_NAME=madam-lite

# Expose port (if needed)
EXPOSE 3333

# Start the Node.js application
# CMD ["npm", "run", "seed:users", "&&", "node", "dist/main.js"]
CMD [ "node", "dist/main.js" ]
